image:
  repository: tccr.io/truecharts/wireshark
  pullPolicy: IfNotPresent
  tag: 4.0.1@sha256:14d1bab7c8e4dd58f88ec917cc6dc51bc7c1910d1dd63f0f0048a1809a816c21

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

hostNetwork: true

service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: HTTP
        port: 3000

probes:
  liveness:
    path: /
  readiness:
    path: /
  startup:
    path: /

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
