image:
  repository: tccr.io/truecharts/papermerge
  pullPolicy: IfNotPresent
  tag: 2.1.5@sha256:987d1fe442ed1fa31f895441d148b8aed38a4facee988344e6b1f690ef9652e5
service:
  main:
    ports:
      main:
        targetPort: 8000
        port: 10141
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
redis:
  enabled: true

  redisUsername: papermerge
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
